<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Polly" Version="8.6.6" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\WorkflowCore\WorkflowCore.csproj" />
    </ItemGroup>

</Project>
