<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <PackageId>SergiiKram.WorkflowCore.DSL</PackageId>
    <Description>DSL extenstion for Workflow Core provding support for JSON and YAML workflow definitions.</Description>
    <Authors>Daniel Gerlag</Authors>
    <Company />
    <Product>WorkflowCore</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SharpYaml" Version="3.7.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkflowCore\WorkflowCore.csproj" />
  </ItemGroup>

</Project>
