<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <PackageId>SergiiKram.WorkflowCore.Providers.Redis</PackageId>
    <PackageLicenseUrl>https://github.com/danielgerlag/workflow-core/blob/master/LICENSE.md</PackageLicenseUrl>
    <RepositoryUrl>https://github.com/danielgerlag/workflow-core.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/danielgerlag/workflow-core</PackageProjectUrl>
    <Description>Redis providers for Workflow Core (Persistence, queueing, distributed locking and event hubs)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RedLock.net" Version="2.3.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\WorkflowCore\WorkflowCore.csproj" />
  </ItemGroup>

</Project>
