<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyTitle>Workflow Core</AssemblyTitle>
    <Authors>Daniel Gerlag</Authors>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <AssemblyName>WorkflowCore</AssemblyName>
    <PackageId>SergiiKram.WorkflowCore</PackageId>
    <PackageTags>workflow;.NET;Core;state machine</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <Description>Workflow Core is a light weight workflow engine targeting .NET Standard.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ConcurrentHashSet" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="2.2.0" />
    <PackageReference Include="NewId" Version="4.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Reflection.TypeExtensions" Version="4.7.0" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.1.0" />
	<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
		<_Parameter1>WorkflowCore.IntegrationTests</_Parameter1>
	</AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\DefinitionStorage\" />
  </ItemGroup>

</Project>
