<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>WorkflowCore.Sample01</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>WorkflowCore.Sample01</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\WorkflowCore\WorkflowCore.csproj" />
  </ItemGroup>

</Project>
